User login registration
ClusterJavaA2020/it-cluster-feedback-project pull request #12
Opened 2020-12-20 23:23 UTC by Iryna97

2020-12-21 08:21 UTC, Forfend requested changes

2020-12-21 08:21 UTC, Forfend commented on src/main/java/com/feedback/controller/UserAuthenticationController.java
> +    public void confirmEmail(@RequestParam("email") String email){
It is better to use the POST HTTP method here

2020-12-21 08:21 UTC, Forfend commented on src/main/java/com/feedback/service/UserServiceImpl.java
> +       User existedUser = user.orElseThrow(UserNotFoundException::new);
```Optional<User> user = userRepo.findUserByEmail(email); User existedUser = user.orElseThrow(UserNotFoundException::new);``` 
can be united

2020-12-21 08:21 UTC, Forfend commented on src/main/java/com/feedback/dto/UserDto.java
> +               // .password(user.getPassword())
remove comment

2020-12-21 08:21 UTC, Forfend commented on src/main/java/com/feedback/controller/UserAuthenticationController.java
> +@CrossOrigin
Probably ```@CrossOrigin``` 
at the global level @kukuruzavictor has already implemented.

2020-12-21 08:24 UTC, kukuruzavictor commented on src/main/java/com/feedback/controller/UserAuthenticationController.java
> +@CrossOrigin
Yep! Just remove the annotation. Should work without it.

2020-12-21 18:42 UTC, Iryna97 commented on src/main/java/com/feedback/controller/UserAuthenticationController.java
> +    public void confirmEmail(@RequestParam("email") String email){
Hello @Forfend , when I use the POST HTTP method, I receive "type=Method Not Allowed, status=405". During my investigation, I figure out that when we didn't provide any information which should be inserted the HTTP protocols don't allow 'POST' because it expects 'GET'.

2020-12-21 20:34 UTC, Iryna97 commented on src/main/java/com/feedback/service/UserServiceImpl.java
> +       User existedUser = user.orElseThrow(UserNotFoundException::new);
Done. Please review.

2020-12-21 20:34 UTC, Iryna97 commented on src/main/java/com/feedback/dto/UserDto.java
> +               // .password(user.getPassword())
Done. Please review.

2020-12-21 20:34 UTC, Iryna97 commented on src/main/java/com/feedback/controller/UserAuthenticationController.java
> +@CrossOrigin
Done. Please review.

2020-12-22 20:04 UTC, Lisanderl requested changes

2020-12-22 20:23 UTC, Iryna97 commented on src/main/java/com/feedback/controller/UserAuthenticationController.java
> +    public void confirmEmail(@RequestParam("email") String email){
Hello @Lisanderl ,
I tried to use RequestBody and PathVariable with POST but got the same error "(type=Method Not Allowed, status=405)."

2020-12-23 22:24 UTC, closed without merging