create deleteFeedbackRequest controller
ClusterJavaA2020/it-cluster-feedback-project pull request #21
Opened 2021-01-27 22:55 UTC by kukuruzavictor

2021-01-29 08:36 UTC, Forfend requested changes

2021-01-29 08:36 UTC, Forfend commented on src/main/java/com/feedback/controller/FeedbackRequestController.java
> +    public FeedbackRequestDto deleteFeedbackRequest(@PathVariable Long courseId,
Why do you return deleted item? It's better to return HTTP status 204 (No Content)

2021-01-29 08:36 UTC, Forfend commented on src/main/java/com/feedback/service/FeedbackRequestServiceImpl.java
> +                feedbackAnswersRepo.delete(feedbackAnswers);
I recommend do not deleting this data, save it for history. Instead, you can do soft-delete. Add new column such as 'deleted' or whatever you want and populate that column here. And do not take into account data that 'deleted' is populated

2021-01-29 21:58 UTC, kukuruzavictor commented on src/main/java/com/feedback/controller/FeedbackRequestController.java
> +    public FeedbackRequestDto deleteFeedbackRequest(@PathVariable Long courseId,
fixed

2021-01-31 20:17 UTC, Forfend approved these changes

2021-02-01 08:54 UTC, merged