Crud user
ClusterJavaA2020/it-cluster-feedback-project pull request #25
Opened 2021-02-16 17:37 UTC by Iryna97

Please review and confirm.
@kukuruzavictor I merged UserServiceIMPL and UserController could you please take a look if your logic was not changed.

2021-02-16 23:05 UTC, kukuruzavictor approved these changes

2021-02-17 09:21 UTC, Forfend requested changes
Please, format the code using shot-ket ```CRTL + ALT + L```

2021-02-17 09:21 UTC, Forfend commented on src/test/java/com/feedback/service/EmailSenderServiceTest.java
> +    public void testSendEmail(){
Please, format the code

2021-02-17 09:21 UTC, Forfend commented on src/test/java/com/feedback/service/AuthenticationServiceImplTest.java
> +    public void testRegisterExistingUser() throws UserAlreadyExistException{
Please, format the code

2021-02-17 09:21 UTC, Forfend commented on src/main/java/com/feedback/service/UserServiceImpl.java
> +public class UserServiceImpl implements UserService{
Please, format the code

2021-02-17 09:21 UTC, Forfend commented on src/main/java/com/feedback/service/AuthenticationServiceImpl.java
> +    public UserDto register(UserDto userDto){
Please, format the code

2021-02-18 14:17 UTC, Forfend approved these changes

2021-02-18 14:18 UTC, Forfend commented
![image](https://user-images.githubusercontent.com/25309882/108370017-dee64280-7204-11eb-91a5-076fd4731499.png)
compilation error

2021-02-18 14:22 UTC, Forfend requested changes
fix compilation error

2021-02-18 15:20 UTC, merged