docker-compose-2
ClusterJavaA2020/it-cluster-feedback-project pull request #30
Opened 2021-02-23 09:09 UTC by javatrap2020

docker-compose-2

2021-02-24 22:35 UTC, Forfend requested changes

2021-02-24 22:35 UTC, Forfend commented on docker-compose.yml
> +version: '3.7'
Any reasons to downgrade the version?

2021-02-24 22:35 UTC, Forfend commented on docker-compose.yml
> +      - feedback-server
Why front-end depends on the back-end?

2021-02-25 09:08 UTC, javatrap2020 commented on docker-compose.yml
> +version: '3.7'
Find a cause of errors to docker-compose. I  do change some versions.  Today change version 3.8, building  the docker-compose - good work. Then I  do change to 3.8 version.

2021-02-25 09:08 UTC, javatrap2020 commented on docker-compose.yml
> +      - feedback-server
I do front-end depends on the back-end for running to end.

2021-02-25 09:10 UTC, Forfend commented on docker-compose.yml
> +      - feedback-server
Will it work without depends on back-end?

2021-02-25 17:01 UTC, javatrap2020 commented on docker-compose.yml
> +version: '3.7'
AWS-not-support 3-8. I checked AWS

2021-02-25 17:02 UTC, javatrap2020 commented on docker-compose.yml
> +version: '3.7'
3-7 docker-compose OK

2021-02-26 09:38 UTC, Forfend approved these changes

2021-02-26 09:38 UTC, merged