feedback counter
ClusterJavaA2020/it-cluster-feedback-project pull request #32
Opened 2021-03-01 13:05 UTC by kukuruzavictor

2021-03-01 19:04 UTC, Forfend requested changes

2021-03-03 13:44 UTC, Forfend commented on src/main/java/com/feedback/service/FeedbackServiceImpl.java
> +                .allFeedback((long) feedbackList.size())
can it be ```int``` in DTO?

2021-03-03 16:36 UTC, kukuruzavictor commented on src/main/java/com/feedback/service/FeedbackServiceImpl.java
> +                .allFeedback((long) feedbackList.size())
Yep :)

2021-03-12 12:16 UTC, Forfend approved these changes

2021-03-17 18:44 UTC, merged